package com.yangg.spring.core.dao;



import java.util.List;

import com.yangg.com.yangg.spring.core.model.MenuInfoExample;
import com.yangg.spring.model.MenuInfo;

public interface MenuInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    int countByExample(MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    int deleteByExample(MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    void insert(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    void insertSelective(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    List<MenuInfo> selectByExample(MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    MenuInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    int updateByExampleSelective(MenuInfo record, MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    int updateByExample(MenuInfo record, MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    int updateByPrimaryKeySelective(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Fri Jan 13 20:57:04 CST 2017
     */
    int updateByPrimaryKey(MenuInfo record);
}