package com.yangg.spring.model;

public class ApplyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_apply.ID
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_apply.ORDER_ID
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_apply.STUTUS
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    private Integer stutus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_apply.ID
     *
     * @return the value of tb_order_apply.ID
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_apply.ID
     *
     * @param id the value for tb_order_apply.ID
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_apply.ORDER_ID
     *
     * @return the value of tb_order_apply.ORDER_ID
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_apply.ORDER_ID
     *
     * @param orderId the value for tb_order_apply.ORDER_ID
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_apply.STUTUS
     *
     * @return the value of tb_order_apply.STUTUS
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public Integer getStutus() {
        return stutus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_apply.STUTUS
     *
     * @param stutus the value for tb_order_apply.STUTUS
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void setStutus(Integer stutus) {
        this.stutus = stutus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", stutus=").append(stutus);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApplyInfo other = (ApplyInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getStutus() == null ? other.getStutus() == null : this.getStutus().equals(other.getStutus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getStutus() == null) ? 0 : getStutus().hashCode());
        return result;
    }
}