package com.yangg.spring.model;

public class MenuInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.ID
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.NAME
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_info.MEMO
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.ID
     *
     * @return the value of tb_menu_info.ID
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.ID
     *
     * @param id the value for tb_menu_info.ID
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.NAME
     *
     * @return the value of tb_menu_info.NAME
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.NAME
     *
     * @param name the value for tb_menu_info.NAME
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_info.MEMO
     *
     * @return the value of tb_menu_info.MEMO
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_info.MEMO
     *
     * @param memo the value for tb_menu_info.MEMO
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", memo=").append(memo);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MenuInfo other = (MenuInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }
}