package com.yangg.spring.model;

public class TbGradeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade_info.ID
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade_info.STUDENT_ID
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade_info.SUBJECCT_ID
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    private String subjecctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade_info.GRADE
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    private String grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade_info.ID
     *
     * @return the value of tb_grade_info.ID
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade_info.ID
     *
     * @param id the value for tb_grade_info.ID
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade_info.STUDENT_ID
     *
     * @return the value of tb_grade_info.STUDENT_ID
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade_info.STUDENT_ID
     *
     * @param studentId the value for tb_grade_info.STUDENT_ID
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade_info.SUBJECCT_ID
     *
     * @return the value of tb_grade_info.SUBJECCT_ID
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public String getSubjecctId() {
        return subjecctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade_info.SUBJECCT_ID
     *
     * @param subjecctId the value for tb_grade_info.SUBJECCT_ID
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public void setSubjecctId(String subjecctId) {
        this.subjecctId = subjecctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade_info.GRADE
     *
     * @return the value of tb_grade_info.GRADE
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade_info.GRADE
     *
     * @param grade the value for tb_grade_info.GRADE
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentId=").append(studentId);
        sb.append(", subjecctId=").append(subjecctId);
        sb.append(", grade=").append(grade);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbGradeInfo other = (TbGradeInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStudentId() == null ? other.getStudentId() == null : this.getStudentId().equals(other.getStudentId()))
            && (this.getSubjecctId() == null ? other.getSubjecctId() == null : this.getSubjecctId().equals(other.getSubjecctId()))
            && (this.getGrade() == null ? other.getGrade() == null : this.getGrade().equals(other.getGrade()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStudentId() == null) ? 0 : getStudentId().hashCode());
        result = prime * result + ((getSubjecctId() == null) ? 0 : getSubjecctId().hashCode());
        result = prime * result + ((getGrade() == null) ? 0 : getGrade().hashCode());
        return result;
    }
}