package com.yangg.spring.dao;

import com.yangg.spring.model.ApplyInfo;
import com.yangg.spring.model.ApplyInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ApplyInfoDAOImpl extends SqlMapClientDaoSupport implements ApplyInfoDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public ApplyInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int countByExample(ApplyInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_order_apply.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int deleteByExample(ApplyInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_order_apply.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void insert(ApplyInfo record) {
        getSqlMapClientTemplate().insert("tb_order_apply.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void insertSelective(ApplyInfo record) {
        getSqlMapClientTemplate().insert("tb_order_apply.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<ApplyInfo> selectByExample(ApplyInfoExample example) {
        List<ApplyInfo> list = getSqlMapClientTemplate().queryForList("tb_order_apply.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByExampleSelective(ApplyInfo record, ApplyInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_order_apply.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByExample(ApplyInfo record, ApplyInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_order_apply.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_apply
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    protected static class UpdateByExampleParms extends ApplyInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, ApplyInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}