package com.yangg.spring.dao;

import com.yangg.spring.model.GoodInfo;
import com.yangg.spring.model.GoodInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GoodInfoDAOImpl extends SqlMapClientDaoSupport implements GoodInfoDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public GoodInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int countByExample(GoodInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_goods_info.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int deleteByExample(GoodInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_goods_info.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int deleteByPrimaryKey(Integer fid) {
        GoodInfo _key = new GoodInfo();
        _key.setFid(fid);
        int rows = getSqlMapClientTemplate().delete("tb_goods_info.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void insert(GoodInfo record) {
        getSqlMapClientTemplate().insert("tb_goods_info.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void insertSelective(GoodInfo record) {
        getSqlMapClientTemplate().insert("tb_goods_info.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<GoodInfo> selectByExample(GoodInfoExample example) {
        List<GoodInfo> list = getSqlMapClientTemplate().queryForList("tb_goods_info.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public GoodInfo selectByPrimaryKey(Integer fid) {
        GoodInfo _key = new GoodInfo();
        _key.setFid(fid);
        GoodInfo record = (GoodInfo) getSqlMapClientTemplate().queryForObject("tb_goods_info.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByExampleSelective(GoodInfo record, GoodInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_goods_info.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByExample(GoodInfo record, GoodInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_goods_info.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByPrimaryKeySelective(GoodInfo record) {
        int rows = getSqlMapClientTemplate().update("tb_goods_info.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByPrimaryKey(GoodInfo record) {
        int rows = getSqlMapClientTemplate().update("tb_goods_info.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    protected static class UpdateByExampleParms extends GoodInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, GoodInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}