package com.yangg.spring.dao;

import com.yangg.spring.model.GoodInfo;
import com.yangg.spring.model.GoodInfoExample;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;

public interface GoodInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int countByExample(GoodInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int deleteByExample(GoodInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    void  insert(GoodInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    void insertSelective(GoodInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    List<GoodInfo> selectByExample(GoodInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    GoodInfo selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByExampleSelective(GoodInfo record, GoodInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByExample(GoodInfo record, GoodInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByPrimaryKeySelective(GoodInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByPrimaryKey(GoodInfo record);
}