package com.yangg.spring.dao;

import com.yangg.spring.model.MenuInfo;
import com.yangg.spring.model.MenuInfoExample;
import com.yangg.spring.page.Page;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MenuInfoDAOImpl extends SqlMapClientDaoSupport implements MenuInfoDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public MenuInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int countByExample(MenuInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_menu_info.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int deleteByExample(MenuInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_menu_info.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        MenuInfo _key = new MenuInfo();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_menu_info.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void insert(MenuInfo record) {
        getSqlMapClientTemplate().insert("tb_menu_info.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void insertSelective(MenuInfo record) {
        getSqlMapClientTemplate().insert("tb_menu_info.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<MenuInfo> selectByExample(MenuInfoExample example) {
        List<MenuInfo> list = getSqlMapClientTemplate().queryForList("tb_menu_info.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public MenuInfo selectByPrimaryKey(Integer id) {
        MenuInfo _key = new MenuInfo();
        _key.setId(id);
        MenuInfo record = (MenuInfo) getSqlMapClientTemplate().queryForObject("tb_menu_info.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByExampleSelective(MenuInfo record, MenuInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_menu_info.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByExample(MenuInfo record, MenuInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_menu_info.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByPrimaryKeySelective(MenuInfo record) {
        int rows = getSqlMapClientTemplate().update("tb_menu_info.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByPrimaryKey(MenuInfo record) {
        int rows = getSqlMapClientTemplate().update("tb_menu_info.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    protected static class UpdateByExampleParms extends MenuInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, MenuInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<MenuInfo> findbyPage(MenuInfoExample example, Page page) {
		// TODO Auto-generated method stub
		return null;
	}
}