package com.yangg.spring.dao;

import com.yangg.spring.model.MenuInfo;
import com.yangg.spring.model.MenuInfoExample;
import com.yangg.spring.model.TbGradeInfo;
import com.yangg.spring.model.TbGradeInfoExample;
import com.yangg.spring.page.Page;

import java.util.List;

import org.springframework.stereotype.Repository;
@Repository
public interface MenuInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int countByExample(MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int deleteByExample(MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    void insert(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    void insertSelective(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    List<MenuInfo> selectByExample(MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    MenuInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByExampleSelective(MenuInfo record, MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByExample(MenuInfo record, MenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByPrimaryKeySelective(MenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByPrimaryKey(MenuInfo record);
    
    public List<MenuInfo> findbyPage(MenuInfoExample example,Page page);
}