package com.yangg.spring.dao;

import com.yangg.spring.model.OrderInfo;
import com.yangg.spring.model.OrderInfoExample;
import java.util.List;

public interface OrderInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int countByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int deleteByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    void insert(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    void insertSelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    List<OrderInfo> selectByExample(OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    OrderInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByExampleSelective(OrderInfo record, OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByExample(OrderInfo record, OrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByPrimaryKeySelective(OrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    int updateByPrimaryKey(OrderInfo record);
}