package com.yangg.spring.dao;

import com.yangg.spring.model.OrderInfo;
import com.yangg.spring.model.OrderInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OrderInfoDAOImpl extends SqlMapClientDaoSupport implements OrderInfoDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public OrderInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int countByExample(OrderInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_order_info.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int deleteByExample(OrderInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_order_info.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int deleteByPrimaryKey(Integer id) {
        OrderInfo _key = new OrderInfo();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_order_info.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void insert(OrderInfo record) {
        getSqlMapClientTemplate().insert("tb_order_info.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public void insertSelective(OrderInfo record) {
        getSqlMapClientTemplate().insert("tb_order_info.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<OrderInfo> selectByExample(OrderInfoExample example) {
        List<OrderInfo> list = getSqlMapClientTemplate().queryForList("tb_order_info.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public OrderInfo selectByPrimaryKey(Integer id) {
        OrderInfo _key = new OrderInfo();
        _key.setId(id);
        OrderInfo record = (OrderInfo) getSqlMapClientTemplate().queryForObject("tb_order_info.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByExampleSelective(OrderInfo record, OrderInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_order_info.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByExample(OrderInfo record, OrderInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_order_info.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByPrimaryKeySelective(OrderInfo record) {
        int rows = getSqlMapClientTemplate().update("tb_order_info.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    public int updateByPrimaryKey(OrderInfo record) {
        int rows = getSqlMapClientTemplate().update("tb_order_info.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_info
     *
     * @mbggenerated Tue Feb 07 17:09:25 CST 2017
     */
    protected static class UpdateByExampleParms extends OrderInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, OrderInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}