package com.yangg.spring.dao;

import com.yangg.spring.model.TbGradeInfo;
import com.yangg.spring.model.TbGradeInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;
@Repository
public class TbGradeInfoDAOImpl extends SqlMapClientDaoSupport implements TbGradeInfoDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public TbGradeInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public int countByExample(TbGradeInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_grade_info.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public int deleteByExample(TbGradeInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_grade_info.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public void insert(TbGradeInfo record) {
        getSqlMapClientTemplate().insert("tb_grade_info.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public void insertSelective(TbGradeInfo record) {
        getSqlMapClientTemplate().insert("tb_grade_info.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    @SuppressWarnings("unchecked")
    public List<TbGradeInfo> selectByExample(TbGradeInfoExample example) {
        List<TbGradeInfo> list = getSqlMapClientTemplate().queryForList("tb_grade_info.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public int updateByExampleSelective(TbGradeInfo record, TbGradeInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_grade_info.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    public int updateByExample(TbGradeInfo record, TbGradeInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_grade_info.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Jan 07 17:13:40 CST 2017
     */
    protected static class UpdateByExampleParms extends TbGradeInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbGradeInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}